services:

  dbdev:
    image: postgres:16
    container_name: galleria-db
    ports:
      - '6500:5432'
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      # POSTGRES_DB: galleria_db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data

volumes:
  postgresDB:
  redis_data:

