version: '3.8'

services:

  app:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis:6379
      - MONGO_URL=mongodb://mongo:27017
    container_name: todo-backend-dev
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 3456:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
    - ./redis_data:/data

volumes:
  mongo_data:
